baseURL = "https://localhost:1313/"
languageCode = "en-us"
title = "Moneo"
theme = "moneo-web"
facebook = "https://facebook.com/itsmoneo"
twitter = "https://twitter.com/itsmoneo"
instagram = "https://instagram.com/moneo_official"
linkedin = "https://linkedin.com/company/itsmoneo"
youtube = "https://youtube.com"

paginate = 9

[taxonomies]
category = "categories"
tag = "tags"
search = "search"

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.algolia]
vars = ["title", "date", "permalink", "author", "thumbnail"]
params = ["categories", "tags"]

[outputs]
home = ["HTML", "RSS", "Algolia"]
